# Generated by Django 5.1.6 on 2025-05-15 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(help_text='Тип имущества (мебель, устройство и т.д.)', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assets/photos/')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('assigned', 'Назначено'), ('free', 'Свободно')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to=settings.AUTH_USER_MODEL)),
                ('pending_user', models.ForeignKey(blank=True, help_text='Кто запросил сейчас', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
