# Generated by Django 5.1.6 on 2025-03-09 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(help_text='Тип имущества (мебель, устройство и т.д.)', max_length=50)),
                ('title', models.CharField(help_text='Название объекта', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Описание объекта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('owner', models.ForeignKey(help_text='Владелец объекта', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
