# Generated by Django 5.1.6 on 2025-05-02 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='pending_user',
            field=models.ForeignKey(blank=True, help_text='Кто запросил сейчас', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('free', 'Свободно'), ('pending', 'Ожидание'), ('assigned', 'Назначено')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Владелец объекта', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
