# Generated by Django 5.1.6 on 2025-05-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='action_type',
            field=models.CharField(blank=True, choices=[('pending', 'На рассмотрении'), ('assigned', 'Назначено'), ('free', 'Свободно')], default='pending', max_length=20, null=True),
        ),
    ]
